DEFAULT_CAMERA_INDEX = 0
DEFAULT_ALIGNMENT_MARGIN_PX = 15
DEFAULT_SERIAL_PORT = "/dev/tty.usbserial-1140"
DEFAULT_BAUD_RATE = 9600

CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30

MASK_KERNEL_SIZE = (5, 5)
MASK_POINTS = 5

ALIGNMENT_THRESHOLD_PX = 15
MAIN_LINE_X_OFFSET_PX = 5
SECONDARY_LINE_X_OFFSET_PX = 5
LEFT_TURN_ERROR_THRESHOLD_PX = -5
RIGHT_TURN_ERROR_THRESHOLD_PX = 5

SIGNAL_ROW_FRACTION = 0.25
LINE_DETECTION_RATIO = 0.6
MAX_FRAMES_WITHOUT_LINE = 10
EXIT_KEY = ord("q")

DARK_LINE_HSV_MIN = (0, 0, 0)
DARK_LINE_HSV_MAX = (180, 255, 50)